[package]
name = "keystone-cc-scenes"
version = "0.1.0"
edition = "2024"

[dependencies]
keystone-cc-core = { path = "../core" }
keystone-cc-adapter = { path = "../adapter" }
keystone-cc-plugins = { path = "../plugins" }
bevy = { workspace = true }
