# Generated by tools/ftl_sheet_exporter.
# Tutorial
stage1-name = Tutorial 1
stage1-text = This is an underground cave deep within a certain forest.
    You were guided here by a faint cat's call coming from somewhere.
    
    Move your body and proceed to the lower levels.
    ____
    Left/Right Action Buttons ... Move left/right
    Jump Button ... Jump over obstacles
    Be careful of crumbling footholds as you advance.
    
    Press F3 (Run) to start.


stage1-description = ...


stage2-name = Tutorial 2
stage2-text = Proceeding underground, a large stone blocked your path.
    You cannot proceed as is.
    ____
    However, in this world, you can convey "how to move" to "special stones"
    and clear your path.
    
    In the left screen, you can write commands on "how to move".
    Write a command to move the blocking stone "down".
    How to write it? Press F4 (Command Help) to find out.
    Then, press F3 (Run) to move the stone according to your command.
    
    If the stone doesn't move as expected, read the explanation carefully and try again.


stage2-description = To move the stone down, try writing the command `{$move-down}`.
    Writing as follows and running it will move the stone up.
    
    {$move-down}


stage3-name = Tutorial 3
stage3-text = A cliff you cannot jump over blocks your way.
    
    However, using the power of the command from earlier, if you ride this stone, it might carry you to the other side.
    You can write commands for the stone to move right continuously.
    ____
    To reach the foothold on the other side, try writing commands as you intend, referring to F4 (Help) here as well.


stage3-description = Stones can be moved not only up but also down, left, and right.
    
    Up: `{$move-up}`
    Down: `{$move-down}`
    Left: `{$move-left}`
    Right: `{$move-right}`
    
    Also, commands can be written consecutively.
    To move the stone left twice in a row:
    
    {$move-left}
    {$move-left}
    
    To move the stone right twice:
    
    {$move-right}
    {$move-right}
    
    You can write it like that.
    Write as many as you need to move and see how the stone moves.


# Basics
stage4-name = Stage 1
stage4-text = A large cliff blocks your path.
    Combine the stone movement methods you've learned so far to cross the cliff.


stage4-description = Stones can move up, down, left, and right.
    
    Up: `{$move-up}`
    Down: `{$move-down}`
    Left: `{$move-left}`
    Right: `{$move-right}`
    
    Also, commands can be written consecutively.
    
    {$move-up}
    {$move-right}
    {$move-down}
    {$move-left}
    
    Writing this will move the stone up, right, down, and left in order.


stage5-name = Stage 2
stage5-text = The stone you want to use as a foothold is a bit far away.
    Let's use the sleep command to wait a little for the stone to move.
    ___
    Check F4 (Command Help) for specific instructions.


stage5-description = Using the {$sleep} command allows you to control the time until the stone moves.
    Passing a number to {$sleep} will stop the stone for that many seconds.
    
    Writing as follows will move the stone right, wait 1 second, and then move up.
    
    {$move-right}
    {$sleep-1}
    {$move-up}
    
    -- Commands so far --
    
    Stone Movement
    Up: `{$move-up}`
    Down: `{$move-down}`
    Left: `{$move-left}`
    Right: `{$move-right}`


stage6-name = Stage 3
stage6-text = This level seems to require a long movement with the stone.
    Using a loop statement allows you to move the stone simply, so press F4 (Command Help) to check how to command it.


stage6-description = If you want to move the stone up forever, using loop saves you the trouble of writing {$move-up} many times.
    
    {$loop-example}
    
    You can also put multiple commands inside a loop.
    
    {$loop-example2}
    
    Writing this will make the stone repeat moving right and waiting for 1 second forever.
    
    -- Commands so far --
    
    Stone Movement
    Up: `{$move-up}`
    Down: `{$move-down}`
    Left: `{$move-left}`
    Right: `{$move-right}`


# Basics 2
stage7-name = Stage 4
stage7-text = The stone seems different from before.
    This stone no longer responds to sleep commands, but instead knows when the player touches it.
    
    Using the detection function is_touched, which knows if the player touched the stone, let's write a command to start moving when the player rides the stone.


stage7-description = Instead of the sleep command, you can use the is_touched command.
    Combining loop and if statements as follows allows you to check if the player is touching, and move the stone in the desired direction while touching.
    
    {$is_touched-example}
    
    loop is a statement used to repeat endlessly, and if, in this case, executes the statement inside if the result of is_touched() is true, and does not execute it if false.
    In other words, it checks if the player is touching forever, and moves the stone only when it judges that it is touching.
    
    -- Commands so far --
    
    Stone Movement
    Up: `{$move-up}`
    Down: `{$move-down}`
    Left: `{$move-left}`
    Right: `{$move-right}`


stage8-name = Stage 5
stage8-text = You have reached a maze-like level.
    The stone has a detection function to check if there is a place to move in the up, down, left, or right directions, or if it is empty.
    ____
    Use the detection function is_empty to determine which path to take and guide the player to the goal.


stage8-description = ...


# Mining
stage9-name = Stage 6
stage9-text = The stone is buried. But this stone seems to be a special stone that can dig around it.
    
    Use the dig command, which allows you to dig around 5 times, to proceed deeper.


stage9-description = ...


stage10-name = Stage 7
stage10-text = In this level, the stone is further blocked by surrounding rocks.
    Combine dig learned in the previous stage and move to let the rock escape.


stage10-description = ...


stage11-name = Stage 8
stage11-text = This level alternates between hollows and rocks.
    Use the dig command, which can only be used 5 times, only when necessary, check with is_empty, and proceed efficiently.


stage11-description = ...


stage13-name = Stage 10
stage13-text = Within a narrow tunnel, you and the stone must pass each other.
    If either one goes too far forward, it will block the other's path, and you won't be able to proceed.
    
    In this stage, let's program a "give way movement" using is_touched_player and sleep, such as:
    
    The stone pauses if the player catches up
    
    Let the player pass first, then the stone starts moving again
    
    If you get stuck, think about "when should I have waited" and rewrite the program.


stage13-description = ...


stage14-name = Stage 11
stage14-text = You wandered into a small maze made of soft rock.
    You could go anywhere if you dig, but you can only mine "3 times".
    
    Where should you dig to connect the path to the goal like a single stroke?
    
    Combine if and is_breakable to devise ways such as:
    
    Judging "Should I really dig here?" before digging
    
    Avoiding useless rocks as much as possible
    
    If you can find the shortest mining route, you will get a step closer to the cat's call.


stage14-description = ...


# Telepathy
stage15-name = Stage 12
stage15-text = This is a wide and quiet underground hall.
    Similar rock pillars line up as far as the eye can see, and you can't tell which way to go just by looking.
    
    In such a place, leaving the stone's direction to the stars is one way.
    Using rand_int(n), you can receive a random value from 0 to n-1.
    
    For example,
    let d = rand_int(4) gets one of 0-3,
    and depending on that value, you can decide whether to move "Up, Right, Down, Left".
    
    While avoiding dangerous directions with is_empty, move the stone according to the guidance of the stars and search for the direction of the cat's call.


stage15-description = ...


stage16-name = Stage 13
stage16-text = Before you, three similar passages spread out.
    None of the passages have traps, and you will eventually return to the same room, but you don't know where the cat will appear from here.
    
    Using rand_int(3), the stars tell you one number from 0 to 2.
    Depending on that value, write a program to decide whether to take the left, middle, or right passage.
    
    While trying several passages leaving it to the stars, find the route that seems to be the shortest.


stage16-description = ...


stage17-name = Stage 14
stage17-text = Not only asking the stars for directions, but also remembering yourself "how far have I advanced" and "how many more times can I dig" will allow you to write more precise movements.
    
    In this stage, create a variable with let and count the number of steps walked and the number of mining times used.
    
    For example, writing:
    
    let steps = 0
    
    move(right)
    steps = steps + 1
    
    
    allows you to record "what step number is this now".
    
    Combine the guidance of the stars and your own notes to aim for the goal with a route with less waste.


stage17-description = ...


stage18-name = Stage 15
stage18-text = In this level, the path will not open unless two stones in separate places cooperate with each other.
    
    Even if they can't see directly, stones can send signals like telepathy to each other.
    
    send(1) ... Send signal "1"
    
    receive(1) ... true if signal "1" is received in that step
    
    With such an image, let's consider coordination where one stone opens the door and the other creates a passage in that gap.
    
    Even if you are alone, the stones will whisper and consult in unseen places to find the path to the cat's voice.


stage18-description = ...


# Final Trial
stage19-name = Stage 16
stage19-text = You have wandered into a multi-layered tunnel that splits up or down and then merges again.
    Soft rocks and switches are scattered around the path, and the place you can reach changes depending on the order you proceed.
    
    Combine what you have learned:
    
    move / sleep
    
    Conditional branching (if) and state check
    
    dig and variables if necessary
    
    Design a route where the stone guides you to each floor in a safe order.
    If you get stuck in a dead end, think about when you should have switched paths and rewrite the program.


stage19-description = ...


stage20-name = Stage 17
stage20-text = In the large dome-shaped hall, cat cries are echoing from all directions.
    Even if you try to proceed relying only on the voice, you don't know which direction determines the real exit.
    
    Let's send out a stone as an explorer and proceed by chasing after it.
    
    While balancing places to move randomly and places to control properly with if and variables, think of such a program that can finally reach the point where the cat's voice is heard loudest.


stage20-description = ...


stage21-name = Stage 18
stage21-text = In this level, there is a stone program already written by someone.
    You can reach the goal even if you run it as is, but it moves inefficiently and uses a lot of time and mining counts.
    
    Here, the goal is to organize that program in your own way.
    Using variables and if, and rand_int if necessary,
    
    Group the same movements
    
    Cut unnecessary commands
    
    Rearrange to make it easier to read
    
    Devise such things and reach the exit where the cat's voice is with shorter and easier-to-understand code.


stage21-description = ...


stage22-name = Stage 19
stage22-text = Finally, you have reached the deepest part of the underground labyrinth.
    From here on, you must use "everything you have learned so far" to enter the hall where the gathering of cats is held.
    
    In this stage, you can freely combine:
    
    Stone movement (move / sleep)
    
    Conditional branching and state check (if, is_empty, is_touched_player, etc.)
    
    Mining (dig) and its count management
    
    Variables, rand_int, telepathy if necessary
    
    Let the stones guide you in the way you understand best.
    If you get through here, you should be able to meet the identity of the cat's call.


stage22-description = ...


stage23-name = Stage 20
stage23-text = After passing the final trial, you found code like old runic characters carved on the cave wall.
    Apparently, it seems to be a stone program written by someone who visited here in the past.
    
    However, if you run it as is, it stops moving halfway or digs the wrong place and becomes a dead end.
    
    In this stage, the purpose is to decipher and fix the already written code.
    While observing where it is moving differently from the intention, let's fix it little by little.


stage23-description = ...
